### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by jennifish1112** [GuiMarion/IDyOM#1]
Hi, I am trying to use IDyOM in python and found your code.
After cloning the App from git, I followed the documentation and tried to install dependencies (`pip install -r requirements.txt`) but there was an error (`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`). I also couldn't find any requirements.txt files from your folder. Do you have any idea what I did wrong? Thanks!

**Comment by GuiMarion** [comment]
Sorry, I never saw your message, the requirements file was not uploaded at the time, I am sorry. It is now! In any case, when the file is missing you can try to install the requirements by looking at the imported modules from the source code.
